[package]
name = "compute-starter-kit-rust-default"
version = "0.1.0"
authors = []
edition = "2018"

[profile.release]
debug = true

[dependencies]
fastly = "^0.6.0"
regex = "1"
log-fastly = "0.1.4"
log = "0.4"
chrono = "0.4"
env_logger = "0.8.3"
json = "0.12.4"