# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["FingerprintJS"]
description = "FingerprintJS Botd integration with Fastly"
language = "rust"
manifest_version = 2
name = "botd-compute-edge"

[local_server]

  [local_server.backends]

    [local_server.backends.backend]
      override_host = "botd-example-app.fpjs.sh"
      url = "http://botd-example-app.fpjs.sh/"

    [local_server.backends.botd]
      override_host = "botd.fpapi.io"
      url = "https://botd.fpapi.io/"

    [local_server.backends.cdn]
      override_host = "script-proxy.edgecompute.app"
      url = "https://script-proxy.edgecompute.app/"

    [local_server.backends.rollbar]
      override_host = "api.rollbar.com"
      url = "https://api.rollbar.com/"

    [local_server.dictionaries.botd_config]
      file = "botd_config.json"
      format = "json"

[setup]

  [setup.backends.botd]
    address = "botd.fpapi.io"
    port = 443
    prompt = "Botd backend"

  [setup.backends.cdn]
    address = "script-proxy.edgecompute.app"
    port = 443
    prompt = "CDN"

  [setup.backends.rollbar]
    address = "api.rollbar.com"
    port = 443
    prompt = "Rollbar"